experiment:
  name: object_a_colmap_dense
  command: run-colmap
  stage: M2_R2

tools:
  ffmpeg: ffmpeg
  colmap: scripts/colmap_clean_env.sh

inputs:
  video_path: data/scene/object_a/raw/object_a.mp4

paths:
  image_dir: data/scene/object_a/frames_dense
  workspace_dir: runs/scene/object_a_colmap_dense/colmap

frame_extraction:
  fps: 3

colmap:
  camera_model: SIMPLE_RADIAL
  single_camera: true
  use_gpu: false
  num_threads: 90

logging:
  enabled: false
  backend: wandb
  project: cvhw3-task1
  mode: offline
